### ISSUE TITLE
WHEN

### ISSUE THREAD

**Issue by MylesBorins** [poutinejs/sf#1]
FEED ME

**Comment by bengl** [comment]
I'm thinking March 1 for the inaugural event?

https://www.facebook.com/madmzelles.poutine

**Comment by DTrejo** [comment]
+1 anytime

**Comment by MylesBorins** [comment]
So last minute I might be out of town on the 1st... fak

**Comment by filipmares** [comment]
In. Can haz calendar invite?

**Comment by bengl** [comment]
aaah crap i can't make it tonight. everyone else: enjoy!

**Comment by DTrejo** [comment]
me neither... too much going on :(

On Sun, Mar 1, 2015 at 10:47 AM, Bryan English notifications@github.com
wrote:

> aaah crap i can't make it tonight. everyone else: enjoy!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poutinejs/sf/issues/1#issuecomment-76623525.

## 

See my projects at dtrejo.com
Read my tips for developers dtrejo.com/blog

**Comment by bengl** [comment]
Closing since this one didn't happen.
